# Default values for assisted-installer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

#
# Service configuration, for more information please see:
# https://github.com/openshift/assisted-service
#
# Any options specified here will be set as environment variables
# These values are just defaults which I know work.
#
config:

  # Generate dummy ignition configs.
  DUMMY_IGNITION: false

  # List of releases and the path to the release image.
  OPENSHIFT_VERSIONS: '{"4.6":{"display_name":"4.6.16","release_version":"4.6.16","release_image":"quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img","rhcos_version":"46.82.202012051820-0","support_level":"production"},"4.7":{"display_name":"4.7.33","release_version":"4.7.33","release_image":"quay.io/openshift-release-dev/ocp-release:4.7.33-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-4.7.33-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-live-rootfs.x86_64.img","rhcos_version":"47.84.202109241831-0","support_level":"production"},"4.8":{"display_name":"4.8.14","release_version":"4.8.14","release_image":"quay.io/openshift-release-dev/ocp-release:4.8.14-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-live-rootfs.x86_64.img","rhcos_version":"48.84.202109241901-0","support_level":"production","default":true},"4.9":{"display_name":"4.9.0","release_version":"4.9.0","release_image":"quay.io/openshift-release-dev/ocp-release:4.9.0-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-live-rootfs.x86_64.img","rhcos_version":"49.84.202110081407-0","support_level":"production"}}'

  # Operating syste mimages and the URL for generating ISO
  OS_IMAGES: '[{"openshift_version":"4.6","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img","version":"46.82.202012051820-0"},{"openshift_version":"4.7","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-4.7.33-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-live-rootfs.x86_64.img","version":"47.84.202109241831-0"},{"openshift_version":"4.8","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-live-rootfs.x86_64.img","version":"48.84.202109241901-0"},{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-live-rootfs.x86_64.img","version":"49.84.202110081407-0"},{"openshift_version":"4.9","cpu_architecture":"arm64","url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-aarch64-live.aarch64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-aarch64-live-rootfs.aarch64.img","version":"49.84.202110080947-0"}]'

  # OCP release version
  RELEASE_IMAGES: '[{"openshift_version":"4.6","cpu_architecture":"x86_64","url":"quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64","version":"4.6.16"},{"openshift_version":"4.7","cpu_architecture":"x86_64","url":"quay.io/openshift-release-dev/ocp-release:4.7.33-x86_64","version":"4.7.33"},{"openshift_version":"4.8","cpu_architecture":"x86_64","url":"quay.io/openshift-release-dev/ocp-release:4.8.14-x86_64","version":"4.8.14","default":true},{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"quay.io/openshift-release-dev/ocp-release:4.9.0-x86_64","version":"4.9.0"},{"openshift_version":"4.9","cpu_architecture":"arm64","url":"quay.io/openshift-release-dev/ocp-release:4.9.0-aarch64","version":"4.9.0"}]'

  # For single node deployments
  ENABLE_SINGLE_NODE_DNSMASQ: true

  # Where public container images are located
  PUBLIC_CONTAINER_REGISTRIES: quay.io

  # ?
  NTP_DEFAULT_SERVER: "ntp1.anu.edu.au"

  # Enable IPV6
  IPV6_SUPPORT: true

  # Values for AUTH_TYPE:
  #
  # * rhsso
  # * none
  # * local
  # * ""
  #
  # RHSSO looks like its tied specficialy to the redhat-single-signon thingo
  # TODO(mhahl): document local.
  #
  AUTH_TYPE: none

  HW_VALIDATOR_REQUIREMENTS: '[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":10},"sno":{"cpu_cores":8,"ram_mib":32768,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10}}]'
  ENABLE_AUTO_ASSIGN: "true"

  # Mandatory
  SERVICE_BASE_URL: "https://assisted-ui.apps.k8s.hahl.id.au"
  ASSISTED_SERVICE_URL: "https://assisted-api.apps.k8s.hahl.id.au"

##
# Configure mirror registry details 
# as well as CA certificates.
#
mirror_registry:
  ca_bundle: |
    -----BEGIN CERTIFICATE-----
    MIIEiDCCAvCgAwIBAgIBATANBgkqhkiG9w0BAQsFADA1MRMwEQYDVQQKDApIQUhM
    LklELkFVMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjEwMTAy
    MDYwNTA3WhcNNDEwMTAyMDYwNTA3WjA1MRMwEQYDVQQKDApIQUhMLklELkFVMR4w
    HAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggGiMA0GCSqGSIb3DQEBAQUA
    A4IBjwAwggGKAoIBgQDXbzotzuoErYG6X2VfdtaD4g3GOPJn/lLJHs+WAPMrubXf
    3FYDJDizXKmb6x/rEbr5xWZ9WMp/tyVbzYmZAzAQb2TyZT81QA2ayGpQJTHnmrnd
    GLm7TuRyIMuC5f/lebNRkXWnCIfmuMHksXhS8Va6lr9GCHNVq3qDuKYiqX1S0rHx
    YlxHSx04GWmQL7AMYeaRX1iZ+6MaAmsiH28B7BalE9UCes2sGkh75VcUCytfF7bo
    RdMSjJjwrudAIUISaaQVCNGRybQ+p/AUxIAUH6OUtzNstaFhkEwC9PwYbNMkZttI
    obg6Ao8YsTtNBVJsVb8xAQ0p9uBFTQdh7JFSUAtf1HhexRxF/bAIIB36EctEIlw/
    TfwXqj6iRWYaAeMA5dn3lbcTrUn+dZXvuy8bqPcvtxiZZ/ZNWdUDH8oAFiFdPGtX
    ol1UUrlf7Jb8+uhcaIXJxqaboVuaGMcT/l5wuzFLLk7BYTZEiS6GwjXHX2FLf8z2
    gtkr6KFntyxiDNinci0CAwEAAaOBojCBnzAfBgNVHSMEGDAWgBR8jVFMRShF8mdK
    dc77hE7qbAORojAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNV
    HQ4EFgQUfI1RTEUoRfJnSnXO+4RO6mwDkaIwPAYIKwYBBQUHAQEEMDAuMCwGCCsG
    AQUFBzABhiBodHRwOi8vaXBhLWNhLmhhaGwuaWQuYXUvY2Evb2NzcDANBgkqhkiG
    9w0BAQsFAAOCAYEA02jUfLByT+onUREFS2DTs7k0ED+dAIpum3pO0rMTT+WrAFIz
    jwauPtpVkvtvZvHe5MvbbxLMtIbz9DByWgyoSfTb3/V4qySS4B4BvKX50LaEfbMc
    7ciAgFhksAjDNRr4AQ0cLljMMMxe4pzNLChdvIm1sh+X6uw5TLI8mUUwwjoIJZ2q
    Fz00251vfouUFvsyPtkk6z7poKV0wQRi490fLvnNdHzfRoscFgQc4eWHApX9zaEU
    db88FxXC4r0k6/v2NrFhx6HyBWt1VTdbHXUBsmG09ImaRYVQzC0eAvkuKR6lWIdO
    mshCULmlHmxeWLJdndM72Cy+Sw6dPtXSj3A2vo8ICimjUPc6E9B3j9ilGtNum9cl
    9N+3Ri2NpAp9PVFoSKxh0pZdIGXAhbjnfC9dZDZ5VXu8HuiwBp63KwY8spTSy33p
    1a3A5Dw38an6nPfCzPHgxCIY1d9AvP805WtgJyvImqxv2J7IYF2/YJ3wmbaldkz+
    5K/Fxr793tmxsLre
    -----END CERTIFICATE-----

  registries_conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "quay.io/ocpmetal"
      mirror-by-digest-only = false

      [[registry.mirror]]
      location = "mirror1.registry.corp.com:5000/ocpmetal"

#
# Options for the assisted-service API.
#
api:
  replicaCount: 3
  image:
    registry: quay.io
    repository: ocpmetal/assisted-service
    tag: latest
    pullPolicy: Always

  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000

  service:
    type: ClusterIP
    port: 8090

  ingress:
    enabled: true
    className: ""
    annotations: {}
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: assisted-api.apps.k8s.hahl.id.au
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

        
  resources:
    limits:
      cpu: 500m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 400Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

# Values for assisted-ui service.

ui:
  replicaCount: 3
  image:
    registry: quay.io
    repository: ocpmetal/ocp-metal-ui
    tag: latest
    pullPolicy: Always

  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: ""
    annotations: {}
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: assisted-ui.apps.k8s.hahl.id.au
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources:
  limits:
      cpu: 100m
      memory: 128Mi
  requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

postgresql:
  postgresqlDatabase: "installer"
  postgresqlUsername: "admin"
  postgresqlPassword: "admin"