apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assisted-installer.fullname" . }}-api
  labels:
    {{- include "assisted-installer.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "assisted-installer.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "assisted-installer.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "assisted-installer.serviceAccountName" . }}
      volumes:
        - name: mirror-registry-conf
          configMap:
            name: {{ include "assisted-installer.fullname" . }}-mirror-registry-conf
            defaultMode: 420
            optional: true
            items:
              - key: registries.conf
                path: registries.conf
        - name: mirror-registry-ca
          configMap:
            name: {{ include "assisted-installer.fullname" . }}-mirror-registry-conf
            defaultMode: 420
            optional: true
            items:
              - key: ca-bundle.crt
                path: mirror_ca.pem
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ include "assisted-installer.fullname" . }}-config
          securityContext:
            {{- toYaml .Values.api.podSecurityContext | nindent 12 }}
          image: "{{ .Values.api.image.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          volumeMounts:
            - name: mirror-registry-ca
              mountPath: "/etc/pki/ca-trust/extracted/pem/mirror_ca.pem"
              readOnly: true
              subPath: mirror_ca.pem
            - name: mirror-registry-conf
              mountPath: "/etc/containers"
              readOnly: true
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8090
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
