apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assisted-installer.fullname" . }}-ui
  labels:
    {{- include "assisted-installer.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "assisted-installer.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "assisted-installer.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "assisted-installer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "assisted-installer.fullname" . }}-nginx
            items:
              - key: nginx.conf
                path: default.conf
      containers:
        - name: {{ .Chart.Name }}
        
          envFrom:
          - configMapRef:
              name: {{ include "assisted-installer.fullname" . }}-config
          securityContext:
            {{- toYaml .Values.ui.podSecurityContext | nindent 12 }}
          image: "{{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          volumeMounts:
            - mountPath: /opt/bitnami/nginx/conf/server_blocks/
              readOnly: true
              name: nginx-conf
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
